export const actions = {
    ADD_NEW_NOTE: "ADD_NEW_NOTE",
    SET_USERNAME: "SET_USERNAME",
    REMOVE_USERNAME: "REMOVE_USERNAME",
    SEARCH_NOTE: "SEARCH_NOTE",
    DELETE_NOTE: "DELETE_NOTE",
  };